// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnGC91huyb5N3IVOntANaHquh2IOzBpgE',
    appId: '1:30452188879:web:18f287917b85b4be7399ba',
    messagingSenderId: '30452188879',
    projectId: 'financapp-d5ff1',
    authDomain: 'financapp-d5ff1.firebaseapp.com',
    storageBucket: 'financapp-d5ff1.firebasestorage.app',
    measurementId: 'G-P6B6JMKSB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeDQxZfLHbxFXCXQy8HPPTHT6OHpL_gHM',
    appId: '1:30452188879:android:2f4b6d84fd403ed67399ba',
    messagingSenderId: '30452188879',
    projectId: 'financapp-d5ff1',
    storageBucket: 'financapp-d5ff1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX5U8ZBrvFUaPxp-NNORZ8iklWxcCuPVE',
    appId: '1:30452188879:ios:64c716ffb4b842327399ba',
    messagingSenderId: '30452188879',
    projectId: 'financapp-d5ff1',
    storageBucket: 'financapp-d5ff1.firebasestorage.app',
    iosBundleId: 'com.example.financApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX5U8ZBrvFUaPxp-NNORZ8iklWxcCuPVE',
    appId: '1:30452188879:ios:64c716ffb4b842327399ba',
    messagingSenderId: '30452188879',
    projectId: 'financapp-d5ff1',
    storageBucket: 'financapp-d5ff1.firebasestorage.app',
    iosBundleId: 'com.example.financApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnGC91huyb5N3IVOntANaHquh2IOzBpgE',
    appId: '1:30452188879:web:4b802860b18a63787399ba',
    messagingSenderId: '30452188879',
    projectId: 'financapp-d5ff1',
    authDomain: 'financapp-d5ff1.firebaseapp.com',
    storageBucket: 'financapp-d5ff1.firebasestorage.app',
    measurementId: 'G-LDDVGEMKHM',
  );
}
